Goal: prep for online migration complete
    - Added docker compose file entries for all
    - Added nginx config and dockerfile for it
    - Added flask supervisor config, gunicorn, and dockerfile
    - Added a script to build frontend and start docker compose

 Changes to be committed:
	modified:   .gitignore
	modified:   admin_dashboard/src/css/CardContent.css
	new file:   api_server/mongo_user.js
	modified:   api_server/start_services.sh
	new file:   api_server/static/images/countries/57133469.png
	new file:   api_server/static/images/countries/58065493.png
	renamed:    api_server/static/images/countries/86955376.png -> api_server/static/images/countries/59414265.png
	modified:   db/docker-entrypoint-initdb.d/mongo_setup.js
	modified:   docker-compose.yml
	deleted:    monitoring/Pipfile.lock
	modified:   monitoring/monitor.py
	new file:   nginx_server/Dockerfile
	new file:   nginx_server/nginx.conf
	new file:   nginx_server/proxy_params
	new file:   nginx_server/start_services.sh
	new file:   package-lock.json
	deleted:    start-server-dev
	modified:   start-server-prod

diff --git a/start-server-prod b/start-server-prod
--- a/start-server-prod
+++ b/start-server-prod
@@ -1,5 +1,31 @@
 #!/bin/bash
 
+
+
+if ! [[ -d nginx_server/build ]]
+then
+    echo "Frontend site not found. Building.... "
+    cd admin_dashboard
+
+    if ! [[ -d node_modules ]] 
+    then
+        echo "Node modules not installed. Installing..."
+        ncu -u 
+        npm install 
+    fi
+
+    npm run build 
+    if [[ ${?} -ne 0 ]]
+    then
+        echo "Error building frontend"
+        exit 1
+    else
+        echo "Frontend built. Moving site..."
+        mv build ../nginx_server/
+    fi
+    cd ..
+fi
+
 echo "Starting production server..."
 docker-compose --env-file docker.production.env up --build ${@}
 
